spring.application.name=learn-vocabulary-be
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.klbbkxulnkgberghuizi
spring.datasource.password=Pqyl7j3W95Cacwku
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudinary.cloud-name=dlm5gmhxs
cloudinary.api-key=761473471196725
cloudinary.api-secret=pbi0nVHDrjHPDA1pNn5dpSQv1A0

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB